import './scss/main.scss';
import './js/header';
import './js/main';
import './js/footer';
// import './js/preLoaderPage';
import './js/language-localstorage';
import './js/submitRegForm';
import './js/submitLogForm';
import './js/userLogOut';
import './js/checkUser';
