import './scss/main.scss';
import './js/header';
import './js/main';
import './js/footer';
import './js/preLoaderPage';
import './js/language-localstorage';
import './js/submitRegLogForm';
import './js/login';
import './js/checkUser';
